version: '3.4'

services:
  postgres:
      image: postgres:13.3
      environment:
        POSTGRES_DB: "finra"
        POSTGRES_USER: "postgres"
        POSTGRES_PASSWORD: "postgres"
      ports:
        - "6543:5432"
  # finraapi:
  #   image: finraapi
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile
  #   ports:
  #     - "8080:5000"