apiVersion: v1
kind: Service
metadata:
  name: finra-api-svc
spec:
  type: NodePort
  selector:
    app: finra-api
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 32001
      protocol: TCP